name: Detect CPU Cores
on: [push]
jobs:
 check-cores:
   runs-on: ubuntu-latest
   steps:
     - name: Get number of CPU cores
       uses: SimenB/github-actions-cpu-cores@v2
       id: cpu-cores
     - name: Show core count
       run: echo "Available cores: ${{ steps.cpu-cores.outputs.count }}"
