name: N-jobs testing PREPROC

on:
  push:
    branches:
      - main
    paths:
      - src/config/config.py
  workflow_dispatch:

permissions:
  contents: write

jobs:
  repreproc:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q

      - name: HPC Retraining
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python src/data/transformation.py

      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            models/model.pkl
            models/preprocessor.pkl
            reports/

#todo comentado para que no edite el modelo

      #- name: Check Model Improvement
      #  id: check_model
      #  env:
      #    PYTHONPATH: ${{ github.workspace }}
      #  run: python src/utils/model_check.py 

      - name: Commit and Push
      #  if: steps.check_model.outcome == 'success' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/
          git diff --cached --quiet || git commit -m "PREPROC actions prueba"
          git push


  # git add models/model.pkl models/preprocessor.pkl reports/
